# .github/workflows/deploy.yml

name: 'Terragrunt Deploy'
  
on:
  push:
    paths:
      - '.github/**'
      - 'modules/**'
      - 'infra/**'
      - 'justfile'
    branches:
      - 'ci/*'
        
jobs:
  deploy-infra:
    uses: fomiller-org/gh-actions/.github/workflows/terragrunt.yaml@generic
    with:
      environment: dev
      infra-dir: infra/modules/aws
      doppler-project: chat-stat
    secrets: inherit
        

