# .github/workflows/deploy.yml

name: 'Terragrunt Deploy'
  
on:
  push:
    paths:
      - '.github/**'
      - 'modules/**'
      - 'infra/**'
      - 'src/**'
      - 'justfile'
      - 'dockerfile'
   
jobs:
  Pre-check:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
            
  Build-lambdas-hello:
    name: 'Build Go lambda'
    needs: Pre-check
    uses: fomiller/gh-actions/.github/workflows/go-lambda.yaml@main
    with:
      lambda_src: src/cmd/lambda/hello/main.go
      lambda_output:  infra/modules/aws/lambda/bin/hello/bootstrap
      artifacts_dir: infra/modules/aws/lambda/bin
        
  # Build-lambda-twitch:
  #   name: 'Build Go lambda'
  #   needs: Pre-check
  #   uses: fomiller/gh-actions/.github/workflows/go-lambda.yaml@main
  #   with:
  #     lambda_src: src/cmd/lambda/twitch/webhookCallback/main.go
  #     lambda_output:  infra/modules/aws/lambda/bin/webhook/bootstrap
  #     artifacts_dir: infra/modules/aws/lambda/bin
        
  Deploy-infra:
    name: 'Deploy Infra'
    needs: [Build-lambdas-hello]
    uses: fomiller/gh-actions/.github/workflows/terragrunt.yaml@main
    with:
      environment: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref) && 'prod' || 'dev' }}
      infra-dir: infra/modules/aws
      doppler-project: chat-stat
      download-artifacts: true
      artifacts_dir: infra/modules/aws/lambda/bin
    secrets: inherit
        
  Build-deploy-ecr-images:
    name: 'Build/Deploy ECR images'
    needs: Deploy-infra
    uses: fomiller/gh-actions/.github/workflows/ecr.yaml@main
    with:
      environment: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref) && 'prod' || 'dev' }}
      repo: api
      repo-prefix: "fomiller-chat-stat"
    secrets: inherit
     
    # use if you need to debug workflow
    # - name: DEBUG
    #   uses: lhotari/action-upterm@v1
    #   with:
    #       limit-access-to-actor: true
    #       limit-access-to-users: Fomiller

